[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[Settings]
  ID = "ed150b7e-da97-4a68-9875-0266f17e55df"